{
 "title": "Service Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Общее количество успешных запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_requests_total{job=\"fastapi\", status=~\"200|201\", handler!=\"/metrics\"}",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Теущая нагрузка на сервис",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total{job=\"fastapi\", handler!=\"/metrics\"})",
     "legendFormat": "Количество запросов на сервис"
    }
   ]
  },
  {
   "title": "Среднее время ответа на /model/generate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_sum{handler=\"/model/generate\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(http_requests_total{handler=\"/model/generate\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Количество HTTP ошибок по кодам",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_total{status=~\"4..|5..\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}